name: tests

trigger: ["*"]
pr: ["*"]

pool:
  vmImage: "ubuntu-18.04"

jobs:
  - job: run_test
    strategy:
      matrix:
        python3_6:
          python.version: "3.6"
        python3_7:
          python.version: "3.7"
        Python3_8:
          python.version: "3.8"
        Python3_9:
          python.version: "3.9"

    timeoutInMinutes: 10

    steps:
      - task: UsePythonVersion@0
        displayName: Set python version
        inputs:
          versionSpec: "$(python.version)"
      - script: |
          set -x  # Echo commands before they are run
          sudo apt-get update
          sudo apt-get install -y build-essential libffi-dev libfuzzy-dev python3-dev
          sudo env "PATH=$PATH" python -m pip install --no-cache-dir -U assemblyline_client click
          sudo env "PATH=$PATH" python -m pip install -U --no-cache-dir -r `pwd`/test/requirements.txt
          sudo rm -rf /tmp/* /var/lib/apt/lists/* ~/.cache/pip
        displayName: Setup Environment
      - script: python -m pytest --durations=10 -rsx -vv
        displayName: Test
